server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.apache.kafka.common.serialization.StringSerializer

ms-producer:
  topic:
    kafka-topic-str: "topic-string-message"